G1 = ["esc"]
G2 = ["tab"]
G3 = ["q"]
G4 = ["w"]
G5 = ["e"]
G6 = ["r"]
G7 = ["t"]
# G8 = 
# G9 = 
G10 = ["a"]
G11 = ["s"]
G12 = ["d"]
G13 = ["f"]
G14 = ["g"]
G15 = ["lshift"]
G16 = ["z"]
G17 = ["x"]
G18 = ["c"]
G19 = ["v"]
G20 = ["lctrl"]
G21 = ["lctrl", "lshift"]
G22 = ["lalt"]
# M1 = 
# M2 = 
# M3 = 
# MR = 
# M0 = 
# D1 = 
# D2 = 
# D3 = 
# D4 = 
# BK = 
# J1 = 
# J2 = 
# J3 = 
